---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: server-services
    version: v1
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: server-services
spec:
  ports:
  - name: http
    port: 8089
    targetPort: 8089
  selector:
    app.kubernetes.io/name: server-services
    version: v1
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    version: v1
    app.kubernetes.io/name: server-services
  name: server-services
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
      version: v1
      app.kubernetes.io/name: server-services
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        version: v1
        app.kubernetes.io/name: server-services
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: R.Subash/server-services:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: server-services
        ports:
        - containerPort: 8089
          name: http
          protocol: TCP
